version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
#      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    expose:
      - '3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis"]
    ports:
      - "6350:6379"
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis
    command: bundle exec sidekiq
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
      - sidekiq
#    command: ["./docker/app/wait-for-it.sh", "mysql:3306", "--", "rails", "server", "-b", "0.0.0.0"]
    environment:
      - RAILS_ENV=${RAILS_ENV}
